FROM debian
MAINTAINER andrewpqc <3480437308@qq.com>

ENV DEPLOY_PATH /xueer-promotion
ENV REDIS_ADDR "<yourhost>:<yourport>"
RUN mkdir -p $DEPLOY_PATH
WORKDIR $DEPLOY_PATH

Add muxi-promotion-service muxi-promotion-service
CMD ./muxi-promotion-service

