apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: promotion-service
  name: promotion-service-svc
spec:
  type: NodePort
  ports:
  - name: "8090"
    port: 8099
    targetPort: 8080
  selector:
    run: promotion-service
status:
  loadBalancer: {}
